/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plasma.donation;

/*import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import oracle.net.aso.a;


*/

import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import oracle.net.aso.n;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author intel
 */
public class profile extends javax.swing.JFrame {

    /**
     * Creates new form profile
     */
    String a;
    int i;
     int diffDays ;
    public profile(String name) {
        initComponents();
        a=name;
               
        jTextField10.setText(a);
       // System.out.println(a);
    }



   profile() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME !!  You are a valuable Donar !!!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("AGE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 126, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("GENDER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("BLOOD GROUP");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("CONTACT NUMBER");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("MAIL ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 128, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("DATE");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("CITY");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("REGISTER ID");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        jTextField3.setEditable(false);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 130, -1));

        jTextField4.setEditable(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 130, -1));

        jTextField5.setEditable(false);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 130, -1));

        jTextField6.setEditable(false);
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 130, -1));

        jTextField7.setEditable(false);
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 130, -1));

        jTextField9.setEditable(false);
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 130, -1));

        jTextField10.setEditable(false);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 130, -1));

        jButton3.setText("Edit Details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, -1, -1));

        jButton4.setText("Delete Account");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, -1, -1));

        jTabbedPane2.addTab("Details", jPanel1);

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Confirm Donate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, -1, -1));

        jLabel10.setText("Name");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        jLabel11.setText("Blood group");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        jLabel15.setText("Contact no");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        jLabel16.setText("Mail Id");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        jLabel17.setText("Register Id");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        jTextField11.setEditable(false);
        jPanel3.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 110, -1));

        jTextField12.setEditable(false);
        jPanel3.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 110, -1));

        jTextField13.setEditable(false);
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 110, -1));

        jTextField14.setEditable(false);
        jPanel3.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 110, -1));

        jTextField15.setEditable(false);
        jPanel3.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 110, -1));

        jLabel18.setText("Status");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        jTextField16.setEditable(false);
        jPanel3.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 110, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 220));

        jTabbedPane2.addTab("Requests", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 720, -1));

        jTabbedPane2.addTab("My Donations", jPanel2);

        jPanel4.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 800, 520));

        jButton2.setText("BACK TO HOMEPAGE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 1550, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
 try{   
                Connection c=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","System","Kalaipapa11"); 
               // jTextField10.setText(name);
                // System.out.println(a);
                String sql2="SELECT * from dons where oid='"+jTextField10.getText()+"' ";
                PreparedStatement stmt=c.prepareStatement(sql2);
                ResultSet r22=stmt.executeQuery();
                 System.out.println(jTextField10.getText());
                // System.out.println(a);
                if(r22.next())
                {  System.out.println(jTextField10.getText());
                 //  System.out.println(a);
                    String DName =r22.getString("oname");
                    String DAge =r22.getString("oage");
                    String DGender =r22.getString("ogender");
                    String DBloodgrp =r22.getString("obloodgrp");
                    String DContno =r22.getString("ocontno");
                   String DDate =r22.getString("odate");
                    String DCity =r22.getString("oaddress");
                    String DMailid =r22.getString("omailid");
                   // String Regid =r.getString("Regid");
                    //System.out.println(a);
                      jTextField1.setText(DName);
                      jTextField2.setText(DAge);
                      jTextField3.setText(DGender);
                      jTextField4.setText(DBloodgrp); 
                      jTextField5.setText(DContno);
                      jTextField6.setText(DDate);
                      jTextField7.setText(DCity);
                      jTextField9.setText(DMailid);           
                }
           else 
                {
                
		JOptionPane.showMessageDialog(null,"Donor Not available");
                c.close();
                        }
              
               }catch(Exception e){System.out.println(e);}
                 
 try{
                Connection c1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","System","Kalaipapa11"); 
                String w="SELECT * from transfer where Bloodgrp='"+jTextField4.getText()+"' ";
                PreparedStatement stmt1=c1.prepareStatement(w);
                ResultSet rt=stmt1.executeQuery();
                
                if(rt.next())
                { 
                    int n=JOptionPane.showOptionDialog(null, "Do you want to donate ??", 
                   "Cancel", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, 
                   null, new Object[] {"Yes", "No"}, JOptionPane.YES_OPTION);

                        if (n == JOptionPane.YES_OPTION) 
                        {          
                           JOptionPane.showMessageDialog(null,"View Requests page to donate !");
      
                                                   
                              

                        }
                        else if(n == JOptionPane.NO_OPTION) {
                              JOptionPane.showMessageDialog(null,"Request Rejected ");  }


                }
                }catch(Exception e){System.out.println(e);}
        
    
       

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  try{
                     Connection cd=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","System","Kalaipapa11"); 
                String d="SELECT tdate from deltran where oid='"+jTextField10.getText()+"' ";
                PreparedStatement stmtd=cd.prepareStatement(d);
                ResultSet rd=stmtd.executeQuery();
                
               
			
                if(rd.next())
                {   
                    String TDate =rd.getString("TDate");
                    System.out.println(TDate);
                    SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd HH:mm");
                Date d1=sdf.parse(TDate);
                Date s=new Date();
                 long diff = s.getTime() - d1.getTime();
                  diffDays = (int) (diff / (24 * 60 * 60 * 1000));
                  System.out.println("HI");
                  System.out.println(TDate);
                  System.out.println("HI");
                System.out.println(d1);
                  System.out.println("HI");
                 System.out.println(diff);
                  System.out.println("HI");
                 System.out.println(s);
                  System.out.println("HI");
                 System.out.println(diffDays);
                }
               
 }     catch(Exception e1){System.out.println(e1);}   

/*
if(diffDays<90)
           {
               JOptionPane.showMessageDialog(null,"You cannot donate since it is not 90 days !! ");  

           }
           else{*/
           
        try{
                                           Connection con20;
                                          con20 = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Kalaipapa11");
                                            
                                          String sql3 = "update transfer set oid='"+jTextField10.getText()+"',TDate=SYSDATE,Action='Donated'  where Rid='"+jTextField15.getText()+"' ";
                                                                                                         // System.out.print(sql);
                                            PreparedStatement st12=con20.prepareStatement(sql3);
                                           ResultSet rs21=st12.executeQuery();
                                         
                                           if(rs21.next()){
                                            JOptionPane.showMessageDialog(null,"Donated successfully :)");
                                            }
                                }     catch(Exception e1){System.out.println(e1);}   
try{
                                           Connection conN;
                                          conN = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Kalaipapa11");
                                            
                                          String sql3 = "DELETE from transfer where Rid='"+jTextField15.getText()+"' ";
                                                                                                         // System.out.print(sql);
                                            PreparedStatement st=conN.prepareStatement(sql3);
                                           ResultSet rs=st.executeQuery();
                                         
                                           if(rs.next()){
                                            JOptionPane.showMessageDialog(null," THANK YOU FOR YOUR HELP :)");
                                            }
                                }     catch(Exception e1){System.out.println(e1);}   
    
         	  try{
Connection conn1=DriverManager .getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Kalaipapa11");
String sql1="select * from DELTRAN where oid='" +jTextField10.getText()+ "' ";
PreparedStatement ps1=conn1.prepareStatement(sql1);
ResultSet rs1=ps1.executeQuery();
jTable3.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs1));
                  }
                  catch(Exception e1){System.out.println(e1);}   
//}
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
try{
Connection conn1=DriverManager .getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Kalaipapa11");
String sql1="select Rid,Bloodgrp,RName,Rcontno,RMailid  from transfer where Bloodgrp='" +jTextField4.getText()+ "' ";
PreparedStatement ps1=conn1.prepareStatement(sql1);
ResultSet rs1=ps1.executeQuery();
jTable2.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs1));
int row = jTable2.getSelectedRow();
jTextField15.setText((String) jTable2.getValueAt(row, 1));

                  }catch(Exception e1)
                  {System.out.println(e1);}        

     

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        homepage h=new homepage();
        this.setVisible(false);
        h.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked


int row = jTable2.getSelectedRow();
jTextField15.setText((String) jTable2.getValueAt(row, 0));
	  try{
Connection conn1=DriverManager .getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Kalaipapa11");
String sql1="select Bloodgrp,RName,RContno,RMailid,Action from transfer where Rid='" +jTextField15.getText()+ "' ";
PreparedStatement ps1=conn1.prepareStatement(sql1);
ResultSet rs1=ps1.executeQuery();     
     if(rs1.next())
                {  System.out.println(jTextField10.getText());
                   
                    String RName =rs1.getString("RName");
                    String Bloodgrp =rs1.getString("Bloodgrp");
                    String RContno =rs1.getString("RContno");
                    String RMailid =rs1.getString("RMailid");
                    String Action =rs1.getString("Action");
                   // String Regid =r.getString("Regid");
                    
                      jTextField11.setText(RName);
                      jTextField12.setText(Bloodgrp);
                      jTextField13.setText(RContno);
                      jTextField14.setText(RMailid); 
                      jTextField16.setText(Action);  
                }
           else 
                {
                
		JOptionPane.showMessageDialog(null,"No Requests !!");
                conn1.close();
                        }     
          }   
catch(Exception e1){System.out.println(e1);}        

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
 try{
Connection conn1=DriverManager .getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Kalaipapa11");
String sql15="select * from DELTRAN where oid='" +jTextField10.getText()+ "' ";
PreparedStatement ps15=conn1.prepareStatement(sql15);
ResultSet rs1=ps15.executeQuery();
jTable3.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs1));
                  }
                  catch(Exception e1){System.out.println(e1);}   

      

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 edit h=new edit(a);
        this.setVisible(false);
        h.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

Delete h=new Delete(a);
                    this.setVisible(false);
                    h.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
